---
# VPC and networking infrastructure tasks

- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
    state: present
    dns_hostnames: "{{ enable_dns_hostnames }}"
    dns_support: "{{ enable_dns_support }}"
    tags: "{{ common_tags | combine({'Name': vpc_name, 'Type': 'VPC'}) }}"
  register: vpc_info

- name: Set VPC ID fact
  set_fact:
    vpc_id: "{{ vpc_info.vpc.id }}"

- name: Display VPC information
  debug:
    msg: "VPC created with ID: {{ vpc_id }}"

- name: Create Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    state: present
    region: "{{ aws_region }}"
    tags: "{{ common_tags | combine({'Name': igw_name, 'Type': 'InternetGateway'}) }}"
  register: igw_info

- name: Set IGW ID fact
  set_fact:
    igw_id: "{{ igw_info.gateway_id }}"

- name: Create public subnets
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ aws_region }}"
    state: present
    map_public: true
    tags: "{{ common_tags | combine({'Name': item.name, 'Type': 'PublicSubnet', 'Tier': 'Public'}) }}"
  register: public_subnets_info
  loop: "{{ public_subnets }}"

- name: Set public subnet IDs fact
  set_fact:
    public_subnet_ids: "{{ public_subnets_info.results | map(attribute='subnet.id') | list }}"

- name: Create private subnets
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ aws_region }}"
    state: present
    map_public: false
    tags: "{{ common_tags | combine({'Name': item.name, 'Type': 'PrivateSubnet', 'Tier': 'Private'}) }}"
  register: private_subnets_info
  loop: "{{ private_subnets }}"

- name: Set private subnet IDs fact
  set_fact:
    private_subnet_ids: "{{ private_subnets_info.results | map(attribute='subnet.id') | list }}"

- name: Create database subnets
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    region: "{{ aws_region }}"
    state: present
    map_public: false
    tags: "{{ common_tags | combine({'Name': item.name, 'Type': 'DatabaseSubnet', 'Tier': 'Database'}) }}"
  register: database_subnets_info
  loop: "{{ database_subnets }}"

- name: Set database subnet IDs fact
  set_fact:
    database_subnet_ids: "{{ database_subnets_info.results | map(attribute='subnet.id') | list }}"

- name: Allocate Elastic IP for NAT Gateway
  ec2_eip:
    region: "{{ aws_region }}"
    in_vpc: true
    state: present
    tags: "{{ common_tags | combine({'Name': nat_eip_name, 'Type': 'ElasticIP'}) }}"
  register: nat_eip
  when: enable_nat_gateway

- name: Create NAT Gateway
  ec2_vpc_nat_gateway:
    subnet_id: "{{ public_subnet_ids[0] }}"
    allocation_id: "{{ nat_eip.allocation_id }}"
    region: "{{ aws_region }}"
    state: present
    tags: "{{ common_tags | combine({'Name': nat_gateway_name, 'Type': 'NATGateway'}) }}"
  register: nat_gateway_info
  when: enable_nat_gateway

- name: Set NAT Gateway ID fact
  set_fact:
    nat_gateway_id: "{{ nat_gateway_info.nat_gateway_id }}"
  when: enable_nat_gateway and nat_gateway_info is defined

- name: Create public route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_id }}"
    subnets: "{{ public_subnet_ids }}"
    tags: "{{ common_tags | combine({'Name': public_route_table_name, 'Type': 'RouteTable'}) }}"
  register: public_rt

- name: Create private route table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ aws_region }}"
    routes: "{{ [{'dest': '0.0.0.0/0', 'gateway_id': nat_gateway_id}] if enable_nat_gateway else [] }}"
    subnets: "{{ private_subnet_ids + database_subnet_ids }}"
    tags: "{{ common_tags | combine({'Name': private_route_table_name, 'Type': 'RouteTable'}) }}"
  register: private_rt

- name: Create VPC Flow Logs
  cloudwatchlogs_log_group:
    log_group_name: "{{ vpc_flow_log_group }}"
    retention: "{{ log_retention_days }}"
    region: "{{ aws_region }}"
    state: present
    tags: "{{ common_tags }}"
  when: enable_flow_logs

- name: Create IAM role for VPC Flow Logs
  iam_role:
    name: "{{ vpc_name }}-flowlogs-role"
    assume_role_policy_document: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "vpc-flow-logs.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    state: present
  register: flowlogs_role
  when: enable_flow_logs

- name: Attach inline policy to Flow Logs role
  iam_policy:
    iam_type: role
    iam_name: "{{ vpc_name }}-flowlogs-role"
    policy_name: "VPCFlowLogsDeliveryPolicy"
    policy_json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents",
              "logs:DescribeLogGroups",
              "logs:DescribeLogStreams"
            ],
            "Resource": "*"
          }
        ]
      }
    state: present
  when: enable_flow_logs and flowlogs_role is defined

- name: Check existing VPC Flow Logs
  shell: >
    aws ec2 describe-flow-logs --filter Name=resource-id,Values={{ vpc_id }} --region {{ aws_region }} --output json
  register: existing_flow_logs
  when: enable_flow_logs
  changed_when: false

- name: Enable VPC Flow Logs
  shell: >
    aws ec2 create-flow-logs 
    --resource-type VPC 
    --resource-ids {{ vpc_id }} 
    --traffic-type ALL 
    --log-destination-type cloud-watch-logs
    --log-group-name {{ vpc_flow_log_group }}
    --deliver-logs-permission-arn {{ flowlogs_role.arn }}
    --region {{ aws_region }}
  when: enable_flow_logs and flowlogs_role is defined and (existing_flow_logs.stdout | from_json).FlowLogs | length == 0

- name: Display VPC deployment summary
  debug:
    msg: |
      VPC Deployment Summary:
      =======================
      VPC ID: {{ vpc_id }}
      Internet Gateway: {{ igw_id }}
      NAT Gateway: {{ nat_gateway_id if enable_nat_gateway else 'Not created' }}
      Public Subnets: {{ public_subnet_ids | length }} created
      Private Subnets: {{ private_subnet_ids | length }} created
      Database Subnets: {{ database_subnet_ids | length }} created
      Flow Logs: {{ 'Enabled' if enable_flow_logs else 'Disabled' }}