---
# Global variables for AWS VPC automation

# Environment configuration
env_name: "production"
project_name: "vpc-automation"
owner: "aws-management-team"

# AWS Region
aws_region: "us-east-1"

# Availability zone
availability_zone: "{{ aws_region }}a"

# VPC Configuration
vpc_cidr: "10.0.0.0/16"
vpc_name: "{{ project_name }}-{{ env_name }}-vpc"

# Subnet Configuration
public_subnets:
  - cidr: "10.0.1.0/24"
    az: "{{ availability_zone }}"
    name: "{{ vpc_name }}-public-subnet"

private_subnets:
  - cidr: "10.0.10.0/24"
    az: "{{ availability_zone }}"
    name: "{{ vpc_name }}-private-subnet"

# Bastion Host Configuration
bastion_ami_id: "ami-0c02fb55956c7d316"  # Amazon Linux 2 AMI (update as needed)
bastion_instance_type: "t2.micro"  # Using t2.micro for testing
bastion_key_pair: "{{ project_name }}-{{ env_name }}-keypair"

# Enable/Disable Components
enable_nat_gateway: true
enable_vpn_gateway: false
enable_flow_logs: true
enable_dns_hostnames: true
enable_dns_support: true
enable_ssm_access: true  # Enable AWS Session Manager for bastion access

# Get current date for tagging
current_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

# Tagging strategy
common_tags:
  Environment: "{{ env_name }}"
  Project: "{{ project_name }}"
  Owner: "{{ owner }}"
  ManagedBy: "Ansible"
  CreatedDate: "{{ current_date }}"
  
# Cost management tags
cost_center: "infrastructure"
billing_code: "aws-management"

# Security configuration
ssh_allowed_ips:
  - "0.0.0.0/0"  # Update this to your office IP range for better security

# Backup and retention
backup_retention_days: 30
log_retention_days: 14

# Notification settings
sns_topic_name: "{{ project_name }}-{{ env_name }}-alerts"
notification_email: "aws-team@company.com"  # Update with actual email