---
# Global variables for AWS VPC automation

# Environment configuration
env_name: "production"
project_name: "vpc-automation"
owner: "aws-management-team"

# AWS Region
aws_region: "us-east-1"

# Availability zones (will use first 2 AZs in the region)
availability_zones:
  - "{{ aws_region }}a"
  - "{{ aws_region }}b"

# VPC Configuration
vpc_cidr: "10.0.0.0/16"
vpc_name: "{{ project_name }}-{{ env_name }}-vpc"

# Subnet Configuration
public_subnets:
  - cidr: "10.0.1.0/24"
    az: "{{ availability_zones[0] }}"
    name: "{{ vpc_name }}-public-subnet-1"
  - cidr: "10.0.2.0/24"
    az: "{{ availability_zones[1] }}"
    name: "{{ vpc_name }}-public-subnet-2"

private_subnets:
  - cidr: "10.0.10.0/24"
    az: "{{ availability_zones[0] }}"
    name: "{{ vpc_name }}-private-subnet-1"
  - cidr: "10.0.20.0/24"
    az: "{{ availability_zones[1] }}"
    name: "{{ vpc_name }}-private-subnet-2"

# Database subnets (for RDS)
database_subnets:
  - cidr: "10.0.50.0/24"
    az: "{{ availability_zones[0] }}"
    name: "{{ vpc_name }}-db-subnet-1"
  - cidr: "10.0.60.0/24"
    az: "{{ availability_zones[1] }}"
    name: "{{ vpc_name }}-db-subnet-2"

# Bastion Host Configuration
bastion_ami_id: "ami-0c02fb55956c7d316"  # Amazon Linux 2 AMI (update as needed)
bastion_instance_type: "t3.micro"
bastion_key_pair: "{{ project_name }}-{{ env_name }}-keypair"

# Enable/Disable Components
enable_nat_gateway: true
enable_vpn_gateway: false
enable_flow_logs: true
enable_dns_hostnames: true
enable_dns_support: true
enable_ssm_access: true  # Enable AWS Session Manager for bastion access

# Tagging strategy
common_tags:
  Environment: "{{ env_name }}"
  Project: "{{ project_name }}"
  Owner: "{{ owner }}"
  ManagedBy: "Ansible"
  CreatedDate: "{{ ansible_date_time.date }}"
  
# Cost management tags
cost_center: "infrastructure"
billing_code: "aws-management"

# Security configuration
ssh_allowed_ips:
  - "0.0.0.0/0"  # Update this to your office IP range for better security

# Backup and retention
backup_retention_days: 30
log_retention_days: 14

# Notification settings
sns_topic_name: "{{ project_name }}-{{ env_name }}-alerts"
notification_email: "aws-team@company.com"  # Update with actual email